### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by Rajdave69** [dhaitz/mplcyberpunk#36]
```
Traceback (most recent call last):
  File "C:\Users\Raj Dave\Desktop\New folder\main.py", line 5, in <module>
    import mplcyberpunk
  File "C:\Users\Raj Dave\AppData\Local\Programs\Python\Python312\Lib\site-packages\mplcyberpunk\__init__.py", line 4, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

python 3.12

happens when I'm trying to import it

**Comment by demming** [comment]
you need `setuptools`, check if you have it

**Comment by ScriptPup** [comment]
If setup tools is required for importing the module, it'd be a good idea to add it to the setup.py install_requires. Though, better would be to ensure it doesn't require setuptools for normal usage. That being said, it's a cool style! Thanks for making it!
